import { Dimensions, StyleSheet } from 'react-native';
import { ThemeColors } from '../../../shared/types/theme.types';

const { width } = Dimensions.get('window');
const gridColumnWidth = Math.max((width - 90) / 7, 60);

/**
 * createStudentStyles(colors) — Strategy Pattern.
 * Tạo style động dựa trên theme hiện tại.
 */
export const createStudentStyles = (colors: ThemeColors) =>
    StyleSheet.create({
        safeArea: {
            flex: 1,
            backgroundColor: colors.background,
        },
        container: {
            flex: 1,
            backgroundColor: colors.background,
        },
        // ── Navbar ──────────────────────────────────────────────────────
        navBarHeader: {
            flexDirection: 'row',
            height: 60,
            backgroundColor: colors.navBar,
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingHorizontal: 15,
            zIndex: 10,
        },
        logo: {
            width: 100,
            height: 40,
        },
        avatar: {
            width: 40,
            height: 40,
            borderRadius: 20,
            backgroundColor: colors.card,
        },
        // ── UserInfo popup ───────────────────────────────────────────────
        userInfoBox: {
            position: 'absolute',
            top: 70,
            right: 15,
            backgroundColor: colors.card,
            padding: 15,
            borderRadius: 8,
            elevation: 5,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.25,
            shadowRadius: 3.84,
            zIndex: 20,
            alignItems: 'center',
        },
        userInfoText: {
            fontSize: 14,
            fontWeight: 'bold',
            marginBottom: 10,
            color: colors.cardText,
        },
        logoutButton: {
            backgroundColor: colors.buttonPrimary,
            paddingVertical: 6,
            paddingHorizontal: 15,
            borderRadius: 4,
        },
        logoutButtonText: {
            color: colors.buttonPrimaryText,
            fontWeight: 'bold',
            fontSize: 12,
        },
        // ── Content ─────────────────────────────────────────────────────
        contentContainer: {
            flex: 1,
            padding: 15,
        },
        phasePanel: {
            backgroundColor: colors.card,
            borderWidth: 1,
            borderColor: colors.tableBorder,
            borderRadius: 8,
            padding: 14,
            marginBottom: 14,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.08,
            shadowRadius: 4,
            elevation: 1,
        },
        phaseKicker: {
            color: colors.textSecondary,
            fontSize: 11,
            fontWeight: 'bold',
            textTransform: 'uppercase',
            marginBottom: 6,
        },
        phaseTitleRow: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: 10,
        },
        phaseTitle: {
            flex: 1,
            color: colors.text,
            fontSize: 20,
            fontWeight: 'bold',
        },
        phaseBadge: {
            minWidth: 74,
            paddingVertical: 5,
            paddingHorizontal: 10,
            borderRadius: 999,
            textAlign: 'center',
            fontSize: 12,
            fontWeight: 'bold',
            overflow: 'hidden',
        },
        phaseBadgeOpen: {
            backgroundColor: '#E8F5EE',
            color: '#087443',
        },
        phaseBadgeClosed: {
            backgroundColor: '#FFF1F0',
            color: '#B42318',
        },
        whatTimeIsIt: {
            fontSize: 16,
            fontWeight: 'bold',
            color: '#8dca1a',
            textAlign: 'center',
            marginVertical: 15,
        },
        actionButton: {
            backgroundColor: colors.buttonSecondary,
            paddingVertical: 12,
            borderRadius: 6,
            alignItems: 'center',
            marginBottom: 20,
        },
        actionButtonText: {
            color: colors.buttonSecondaryText,
            fontWeight: 'bold',
            fontSize: 16,
        },
        searchInput: {
            flex: 1,
            height: 50,
            borderWidth: 1,
            borderColor: colors.inputBorder,
            borderRadius: 6,
            paddingHorizontal: 15,
            fontSize: 16,
            backgroundColor: colors.inputBackground,
            color: colors.inputText,
        },
        registrationPanel: {
            backgroundColor: colors.card,
            borderWidth: 1,
            borderColor: colors.tableBorder,
            borderRadius: 8,
            padding: 14,
            marginBottom: 16,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.08,
            shadowRadius: 4,
            elevation: 1,
        },
        panelHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'flex-start',
            gap: 12,
            marginBottom: 12,
        },
        panelTitleBlock: {
            flex: 1,
        },
        panelTitle: {
            color: colors.text,
            fontSize: 17,
            fontWeight: 'bold',
        },
        panelSubtitle: {
            color: colors.textSecondary,
            fontSize: 12,
            marginTop: 3,
        },
        outlineActionButton: {
            minHeight: 34,
            borderWidth: 1,
            borderColor: colors.buttonPrimary,
            borderRadius: 6,
            paddingHorizontal: 12,
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: colors.card,
        },
        outlineActionButtonText: {
            color: colors.buttonPrimary,
            fontSize: 12,
            fontWeight: 'bold',
        },
        searchRow: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 10,
        },
        registerButton: {
            backgroundColor: colors.buttonPrimary,
            height: 50,
            paddingHorizontal: 14,
            borderRadius: 6,
            alignItems: 'center',
            justifyContent: 'center',
        },
        registerButtonDisabled: {
            opacity: 0.65,
        },
        registerButtonText: {
            color: colors.buttonPrimaryText,
            fontWeight: 'bold',
            fontSize: 16,
        },
        // ── Bảng đăng ký ────────────────────────────────────────────────
        tableContainer: {
            marginBottom: 30,
            backgroundColor: colors.card,
            borderWidth: 1,
            borderColor: colors.tableBorder,
            borderRadius: 8,
            padding: 12,
        },
        sectionTitle: {
            fontSize: 16,
            fontWeight: 'bold',
            color: colors.text,
            marginBottom: 10,
        },
        table: {
            borderWidth: 1,
            borderColor: colors.tableBorder,
        },
        tableHeader: {
            flexDirection: 'row',
            backgroundColor: colors.tableHeader,
            borderBottomWidth: 1,
            borderBottomColor: colors.tableBorder,
        },
        tableRow: {
            flexDirection: 'row',
            borderBottomWidth: 1,
            borderBottomColor: colors.tableBorder,
        },
        headerCell: {
            padding: 10,
            fontWeight: 'bold',
            fontSize: 12,
            color: colors.tableHeaderText,
            textAlign: 'center',
        },
        cell: {
            padding: 10,
            fontSize: 12,
            color: colors.tableCell,
            textAlign: 'center',
        },
        courseCodeText: {
            color: colors.buttonPrimary,
            fontWeight: 'bold',
        },
        cellId: { width: 50 },
        cellCode: { width: 80 },
        cellName: { width: 180 },
        cellStatus: { width: 100 },
        cellCredits: { width: 60 },
        tableStatusCell: {
            padding: 8,
            justifyContent: 'center',
            alignItems: 'center',
        },
        tableStatusText: {
            minWidth: 76,
            textAlign: 'center',
            borderRadius: 999,
            overflow: 'hidden',
            paddingVertical: 3,
            paddingHorizontal: 8,
            fontSize: 11,
            fontWeight: 'bold',
        },
        // ── Time Grid ────────────────────────────────────────────────────
        timeGrid: {
            borderWidth: 1,
            borderColor: colors.tableBorder,
        },
        gridRow: { flexDirection: 'row' },
        gridHeaderCorner: {
            width: 60,
            height: 40,
            backgroundColor: colors.tableHeader,
            borderRightWidth: 1,
            borderBottomWidth: 1,
            borderColor: colors.tableBorder,
        },
        gridHeaderCell: {
            width: gridColumnWidth,
            height: 40,
            backgroundColor: colors.tableHeader,
            justifyContent: 'center',
            alignItems: 'center',
            borderRightWidth: 1,
            borderBottomWidth: 1,
            borderColor: colors.tableBorder,
        },
        gridHeaderText: {
            fontWeight: 'bold',
            fontSize: 12,
            color: colors.tableHeaderText,
        },
        gridPeriodCell: {
            width: 60,
            height: 50,
            backgroundColor: colors.surface,
            justifyContent: 'center',
            alignItems: 'center',
            borderRightWidth: 1,
            borderBottomWidth: 1,
            borderColor: colors.tableBorder,
        },
        gridPeriodText: {
            fontSize: 12,
            color: colors.textSecondary,
        },
        gridCell: {
            width: gridColumnWidth,
            height: 50,
            justifyContent: 'center',
            alignItems: 'center',
            borderRightWidth: 1,
            borderBottomWidth: 1,
            borderColor: colors.tableBorder,
            backgroundColor: colors.background,
        },
        gridCellActive: {
            backgroundColor: '#E6F3FF',
        },
        gridEventText: {
            fontSize: 10,
            color: '#0055A4',
            textAlign: 'center',
            padding: 2,
        },
        gridDivider: {
            backgroundColor: colors.tableBorder,
            height: 20,
            justifyContent: 'center',
            alignItems: 'center',
        },
        gridDividerText: {
            fontSize: 10,
            color: colors.textSecondary,
            fontWeight: 'bold',
        },
        bottomSpacer: { height: 40 },
        curriculumHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 12,
            padding: 15,
            backgroundColor: colors.navBar,
            borderBottomWidth: 1,
            borderBottomColor: colors.tableBorder,
        },
        curriculumTitleBlock: {
            flex: 1,
        },
        curriculumTitle: {
            color: colors.buttonPrimaryText,
            fontSize: 18,
            fontWeight: 'bold',
        },
        curriculumSubtitle: {
            color: colors.buttonPrimaryText,
            fontSize: 12,
            marginTop: 2,
        },
        backButton: {
            backgroundColor: colors.buttonSecondary,
            paddingVertical: 8,
            paddingHorizontal: 12,
            borderRadius: 4,
        },
        backButtonText: {
            color: colors.buttonSecondaryText,
            fontWeight: 'bold',
            fontSize: 12,
        },
        inlineActionButton: {
            backgroundColor: colors.buttonPrimary,
            paddingVertical: 6,
            paddingHorizontal: 8,
            borderRadius: 4,
            alignSelf: 'center',
        },
        curriculumActionCell: {
            width: 100,
            padding: 6,
            justifyContent: 'center',
            alignItems: 'center',
        },
        inlineActionButtonText: {
            color: colors.buttonPrimaryText,
            fontWeight: 'bold',
            fontSize: 11,
        },
        mutedCellText: {
            color: colors.textSecondary,
            textAlign: 'center',
        },
        summaryGrid: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            gap: 10,
            marginBottom: 14,
        },
        summaryCard: {
            width: '48%',
            backgroundColor: colors.card,
            borderWidth: 1,
            borderColor: colors.tableBorder,
            borderRadius: 8,
            padding: 12,
        },
        summaryLabel: {
            color: colors.textSecondary,
            fontSize: 11,
            fontWeight: 'bold',
            textTransform: 'uppercase',
        },
        summaryValue: {
            color: colors.text,
            fontSize: 22,
            fontWeight: 'bold',
            marginTop: 4,
        },
        // ── Gợi ý học phần (Suggestions Dropdown) ────────────────────────────────────
        suggestionsContainer: {
            backgroundColor: colors.card,
            borderColor: colors.inputBorder,
            borderWidth: 1,
            borderRadius: 8,
            marginTop: 10,
            maxHeight: 240,
            overflow: 'hidden',
            zIndex: 30,
            elevation: 3,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.2,
            shadowRadius: 1.41,
        },
        suggestionItem: {
            padding: 12,
            borderBottomWidth: 1,
            borderBottomColor: colors.separator,
        },
        suggestionMainRow: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            gap: 10,
            marginBottom: 3,
        },
        suggestionCode: {
            color: colors.buttonPrimary,
            fontSize: 14,
            fontWeight: 'bold',
        },
        suggestionCredits: {
            color: colors.textSecondary,
            fontSize: 12,
            fontWeight: 'bold',
        },
        suggestionText: {
            fontSize: 14,
            color: colors.text,
        },
        suggestionStateText: {
            color: colors.textSecondary,
            padding: 12,
            fontSize: 14,
        },
        suggestionErrorText: {
            color: '#B42318',
            padding: 12,
            fontSize: 14,
        },
        suggestionStatus: {
            alignSelf: 'flex-start',
            marginTop: 8,
            borderRadius: 999,
            paddingVertical: 3,
            paddingHorizontal: 9,
            overflow: 'hidden',
            fontSize: 12,
            fontWeight: 'bold',
        },
        statusCompleted: {
            backgroundColor: '#E8F5EE',
            color: '#087443',
        },
        statusUnlearned: {
            backgroundColor: '#F2F4F7',
            color: '#667085',
        },
        statusRegistered: {
            backgroundColor: '#EDF4FF',
            color: '#175CD3',
        },
        statusAvailable: {
            backgroundColor: '#FFF7E6',
            color: '#B54708',
        },
        statusBlocked: {
            backgroundColor: '#FFF1F0',
            color: '#B42318',
        },
        // ── Trạng thái đóng đăng ký (No active phase notice) ─────────────────────────
        noPhaseContainer: {
            alignItems: 'center',
            justifyContent: 'center',
            paddingVertical: 50,
            paddingHorizontal: 20,
            backgroundColor: colors.surface,
            borderRadius: 8,
            borderWidth: 1,
            borderColor: colors.tableBorder,
            marginTop: 20,
        },
        noPhaseIcon: {
            fontSize: 48,
            marginBottom: 15,
        },
        noPhaseTitle: {
            fontSize: 18,
            fontWeight: 'bold',
            color: colors.text,
            textAlign: 'center',
            marginBottom: 10,
        },
        noPhaseSubText: {
            fontSize: 14,
            color: colors.textSecondary,
            textAlign: 'center',
        },
    });
